apiVersion: v2
name: standalone-edc
description: Standalone Eclipse Dataspace Connector (control-plane + data-plane)
type: application
version: 0.1.0
appVersion: "v0.15.0"   # checked out tag


dependencies:
  - name: postgresql
    version: 15.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  # - name: vault
  #   version: 0.27.0
  #   repository: https://helm.releases.hashicorp.com
  #   condition: vault.enabled
